#!/bin/sh

while true; do
  echo "$(date): Pruning old deployments"
  oc adm prune deployments --orphans --confirm
  echo

  echo "$(date): Pruning old builds"
  oc adm prune builds --orphans --confirm
  echo

  echo "$(date): Pruning old images from registry"
  oc adm prune images --confirm
  echo

  echo "$(date): Pruning images over size limit from registry"
  oc adm prune images --prune-over-size-limit --confirm
  echo

  sleep 3600
done
